"""empty message

Revision ID: 031d26de3783
Revises: 14b0a557f967
Create Date: 2023-05-25 01:07:49.919522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031d26de3783'
down_revision = '14b0a557f967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
