"""empty message

Revision ID: 0545b3c86a6a
Revises: f87712d76659
Create Date: 2023-05-28 17:17:44.941145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0545b3c86a6a'
down_revision = 'f87712d76659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('direction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direction_name'), ['name'], unique=False)

    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('social_network', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_direction_id'), ['direction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_user_id'), ['user_id'], unique=False)

    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('social_network', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacancy_direction_id'), ['direction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancy_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancy_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancy_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('scale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scale_test_id'), ['test_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_about'), ['about'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_salary'), ['salary'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_salary'))
        batch_op.drop_index(batch_op.f('ix_user_about'))
        batch_op.drop_column('about')
        batch_op.drop_column('salary')

    with op.batch_alter_table('scale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scale_test_id'))
        batch_op.drop_column('test_id')

    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancy_user_id'))
        batch_op.drop_index(batch_op.f('ix_vacancy_name'))
        batch_op.drop_index(batch_op.f('ix_vacancy_email'))
        batch_op.drop_index(batch_op.f('ix_vacancy_direction_id'))

    op.drop_table('vacancy')
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_user_id'))
        batch_op.drop_index(batch_op.f('ix_resume_name'))
        batch_op.drop_index(batch_op.f('ix_resume_email'))
        batch_op.drop_index(batch_op.f('ix_resume_direction_id'))

    op.drop_table('resume')
    with op.batch_alter_table('direction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direction_name'))

    op.drop_table('direction')
    # ### end Alembic commands ###
