"""Add Direction, Resume tables

Revision ID: 14b0a557f967
Revises: 81687fd2427b
Create Date: 2023-05-24 23:36:18.953246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b0a557f967'
down_revision = '81687fd2427b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('direction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direction_name'), ['name'], unique=False)

    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('social_network', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_direction_id'), ['direction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_user_id'))
        batch_op.drop_index(batch_op.f('ix_resume_name'))
        batch_op.drop_index(batch_op.f('ix_resume_email'))
        batch_op.drop_index(batch_op.f('ix_resume_direction_id'))

    op.drop_table('resume')
    with op.batch_alter_table('direction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direction_name'))

    op.drop_table('direction')
    # ### end Alembic commands ###
