"""empty message

Revision ID: 7661930e8d66
Revises: 031d26de3783
Create Date: 2023-05-25 22:23:57.536615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7661930e8d66'
down_revision = '031d26de3783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
