"""Add Right_level_access

Revision ID: 81687fd2427b
Revises: 735a98c1e33e
Create Date: 2023-05-24 23:32:20.231999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81687fd2427b'
down_revision = '735a98c1e33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('right_level_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('functional_name', sa.String(length=64), nullable=True),
    sa.Column('right_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('right_level_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_right_level_access_functional_name'), ['functional_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_right_level_access_right_level'), ['right_level'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('right_level_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_right_level_access_right_level'))
        batch_op.drop_index(batch_op.f('ix_right_level_access_functional_name'))

    op.drop_table('right_level_access')
    # ### end Alembic commands ###
