"""empty message

Revision ID: a1a6588a2fef
Revises: 8d3862646368
Create Date: 2023-05-26 22:04:31.335414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a6588a2fef'
down_revision = '8d3862646368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_test_name')
        batch_op.create_index(batch_op.f('ix_test_title'), ['title'], unique=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_test_title'))
        batch_op.create_index('ix_test_name', ['name'], unique=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
